package Menu;

import DBEngine.DBEngine;
import QuanLyLapTop.LapTopGUI;
import QuanLyTablet.TabletGUI;
import User.GUI_ManagerUser;
import User.User;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import quanlyphukien.PhuKienGUI;


public class GUI_Menu extends javax.swing.JFrame {
    ArrayList<User> listUser;
    DBEngine db = new DBEngine();
    private boolean isAuthenticated = false;
    private String role = GUI_Login.getRole();
    String fileName = "user.txt";
    /**
     * Creates new form GUI_Menu
     */
    public void loadData(){
        try {
            listUser = (ArrayList<User>) db.readFile(fileName);
        } catch (Exception err) {
            System.out.println(err.toString());
        }
    }
    public GUI_Menu() {
        initComponents();
        getContentPane().setBackground(new Color(242,242,242));
        setTitle("Menu");
        loadData();
        btnTK.setEnabled(false);
        if("admin".equals(GUI_Login.getRole())){
            btnTK.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLaptop = new javax.swing.JButton();
        btnPK = new javax.swing.JButton();
        btnTablet = new javax.swing.JButton();
        btnTK = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnInformation = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/setup.png"))); // NOI18N
        jLabel1.setText("CHƯƠNG TRÌNH QUẢN LÝ");

        btnLaptop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLaptop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laptopLogo.jpg"))); // NOI18N
        btnLaptop.setText("Quản lý laptop");
        btnLaptop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaptopActionPerformed(evt);
            }
        });

        btnPK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ramLogo.jpg"))); // NOI18N
        btnPK.setText("Quản lý phụ kiện");
        btnPK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPKActionPerformed(evt);
            }
        });

        btnTablet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTablet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tablet logo.jpg"))); // NOI18N
        btnTablet.setText("Quản lý Tablet");
        btnTablet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabletActionPerformed(evt);
            }
        });

        btnTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UserLogo.png"))); // NOI18N
        btnTK.setText("Quản lý tài khoản");
        btnTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKActionPerformed(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/infomation.jpg"))); // NOI18N
        btnInformation.setToolTipText("");
        btnInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformationActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_3.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText(GUI_Login.getUserName());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Xin chào");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 266, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInformation)))
                        .addGap(39, 39, 39))))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPK, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTablet, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTablet, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInformation, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformationActionPerformed
        GUI_Information gui = new GUI_Information();
        gui.setVisible(true);
        gui.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnInformationActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        GUI_Login gui = new GUI_Login();
        gui.setVisible(true);
        gui.setLocationRelativeTo(null);
        GUI_Menu.this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKActionPerformed
        String code = GUI_Login.getUserCode();
        for(User u : listUser) {
            if(code.equals(u.getMaNV())){
                isAuthenticated = true;
                break;
            }
        }
        try {
            if(isAuthenticated){
                if(role.equals("admin")){
                    GUI_ManagerUser gui = new GUI_ManagerUser();
                    gui.setVisible(true);
                    gui.setLocationRelativeTo(null);
                    GUI_Menu.this.dispose(); 
                } else {
                    JOptionPane.showMessageDialog(null, "Tài khoản admin mới có thể truy cập!","Error",JOptionPane.INFORMATION_MESSAGE);
                }         
            } 
        } catch(Exception err) {
            JOptionPane.showMessageDialog(null, err.toString(),"Error",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnTKActionPerformed

    private void btnPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPKActionPerformed
        try {
            PhuKienGUI gui = new PhuKienGUI();
            gui.setVisible(true);
            gui.setLocationRelativeTo(null);
            GUI_Menu.this.dispose();
        } catch(Exception err) {
            JOptionPane.showMessageDialog(null, err.toString(),"Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPKActionPerformed

    private void btnLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaptopActionPerformed
        try {
            LapTopGUI gui = new LapTopGUI();
            gui.setVisible(true);
            gui.setLocationRelativeTo(null);
            GUI_Menu.this.dispose();
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err.toString(),"Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLaptopActionPerformed

    private void btnTabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabletActionPerformed
        try {
            TabletGUI gui = new TabletGUI();
            gui.setVisible(true);
            gui.setLocationRelativeTo(null);
            GUI_Menu.this.dispose();
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err.toString(),"Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnTabletActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformation;
    private javax.swing.JButton btnLaptop;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPK;
    private javax.swing.JButton btnTK;
    private javax.swing.JButton btnTablet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
